

version: '2.1'

volumes:
    ros-bin: 

services:
  roscore:
    image: cristidragomir97/roscore
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=roscore
       - ROS_MASTER_URI=http://roscore:11311
    links: 
      - motionbox
    ports:
      - "11311:11311"
    volumes:
      - ros-bin:/opt/ros/noetic

  motionbox:
    privileged: true
    build: .
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=motionblock
       - ROS_MASTER_URI=http://roscore:11311
    volumes:
      - ros-bin:/opt/ros/noetic
    ports:
      - "8000:80"
      - "5000:5000"
    devices:
      - "/dev:/dev"
